//! ACAD_GROUP object (spec §19.6.7 — L6-11) — named, ordered set of
//! entity handles.
//!
//! Groups are user-visible selection sets exposed via the GROUP
//! command. They behave like a loose collection: members retain
//! their own ownership (block record, layout) but the group holds
//! soft-pointer references to them.
//!
//! # Stream shape — measured
//!
//! ```text
//! TV      name                  -- group description; empty in practice
//! BS      unnamed               -- non-zero for AutoCAD-generated "*A" groups
//! BS      selectable            -- non-zero if selecting a member selects all
//! BL      num_members
//! ```
//!
//! The member handles are handle references, not data-stream fields, so
//! they are not read here; the *i*-th of them is the *i*-th member.
//!
//! An earlier cut read `B unnamed, B selectable` and then the handles
//! inline. Both GROUP records of `sample_AC1032.dwg` (handles 1430 and
//! 1437) say otherwise: each leaves exactly 30 bits between the end of
//! its common object data and the start of its string stream, spent as
//! three 10-bit fields — `BS` = 2, `BS` = 1, `BL` = 6 — with the name
//! in the string stream. Two single-bit flags plus a `BL` cannot fill
//! 30 bits, and reading them that way runs the `BL` off the end of the
//! record, which is what made both records fail to decode.
//!
//! The first field reading 2 rather than the 0/1 a boolean would
//! suggest is why it is surfaced as a raw [`i16`]: the width is
//! established by the bytes, the semantics of that particular value are
//! not, and this crate has no second file with a GROUP record to
//! cross-check against.
//!
//! The `num_members` count is capped at 100 000 per spec-safety
//! guidance: real drawings rarely exceed a few hundred group
//! members, and an unbounded count from an adversarial file would
//! otherwise allow a decompression-bomb-adjacent allocation vector.

use crate::bitcursor::BitCursor;
use crate::error::{Error, Result};
use crate::objects::modern;
use crate::string_stream::StringReader;
use crate::version::Version;

/// Maximum GROUP member handle count honored by the decoder.
const MAX_GROUP_HANDLES: usize = 100_000;

/// Decoded ACAD_GROUP body.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct AcadGroup {
    pub name: String,
    /// Raw `BS`; non-zero on AutoCAD-generated `*A…` groups. See the
    /// module docs on why this is not a `bool`.
    pub unnamed: i16,
    /// Raw `BS`; non-zero when selecting one member selects the group.
    pub selectable: i16,
    /// How many member handles follow the data stream. The handles
    /// themselves are handle references, not data-stream fields.
    pub num_members: u32,
}

impl AcadGroup {
    /// Was this group generated by AutoCAD rather than named by a user?
    pub fn is_unnamed(&self) -> bool {
        self.unnamed != 0
    }

    /// Does selecting one member select the whole group?
    pub fn is_selectable(&self) -> bool {
        self.selectable != 0
    }
}

/// Read the ACAD_GROUP field list from whichever streams hold it.
fn read_body(
    c: &mut BitCursor<'_>,
    strings: &mut Option<StringReader<'_>>,
    version: Version,
) -> Result<AcadGroup> {
    let name = modern::read_tv(c, strings, version)?;
    let unnamed = c.read_bs()?;
    let selectable = c.read_bs()?;
    let num_members = c.read_bl()? as usize;
    if num_members > MAX_GROUP_HANDLES {
        return Err(Error::SectionMap(format!(
            "ACAD_GROUP claims {num_members} member handles (>{MAX_GROUP_HANDLES} sanity cap)"
        )));
    }
    Ok(AcadGroup {
        name,
        unnamed,
        selectable,
        num_members: num_members as u32,
    })
}

/// Decodes the `AcadGroup` payload that follows the common object header.
pub fn decode(c: &mut BitCursor<'_>, version: Version) -> Result<AcadGroup> {
    read_body(c, &mut None, version)
}

/// Decode an ACAD_GROUP straight from its raw object payload, taking
/// the group name from the R2007+ string stream when the file has one
/// and checking the data fields end exactly on the data-stream
/// boundary.
pub(crate) fn decode_object(
    payload: &[u8],
    body_start: usize,
    inline_data_end: Option<usize>,
    version: Version,
) -> Result<AcadGroup> {
    let mut split = modern::open(payload, body_start, inline_data_end, version)?;
    let out = read_body(&mut split.data, &mut split.strings, version)?;
    split.finish("ACAD_GROUP")?;
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::bitwriter::BitWriter;

    fn encode_tv_r2000(w: &mut BitWriter, s: &[u8]) {
        w.write_bs_u(s.len() as u16);
        for b in s {
            w.write_rc(*b);
        }
    }

    #[test]
    fn roundtrip_empty_group() {
        let mut w = BitWriter::new();
        encode_tv_r2000(&mut w, b"MyGroup");
        w.write_bs(0); // named
        w.write_bs(1); // selectable
        w.write_bl(0);
        let bytes = w.into_bytes();
        let mut c = BitCursor::new(&bytes);
        let g = decode(&mut c, Version::R2000).unwrap();
        assert_eq!(g.name, "MyGroup");
        assert!(!g.is_unnamed());
        assert!(g.is_selectable());
        assert_eq!(g.num_members, 0);
    }

    #[test]
    fn roundtrip_populated_group() {
        let mut w = BitWriter::new();
        encode_tv_r2000(&mut w, b"*A1");
        w.write_bs(2); // unnamed (AutoCAD-generated)
        w.write_bs(0); // not selectable as a whole
        w.write_bl(2);
        let bytes = w.into_bytes();
        let mut c = BitCursor::new(&bytes);
        let g = decode(&mut c, Version::R2000).unwrap();
        assert_eq!(g.name, "*A1");
        assert!(g.is_unnamed());
        assert!(!g.is_selectable());
        assert_eq!(g.num_members, 2);
    }

    /// The exact field widths of `sample_AC1032.dwg`'s two GROUP
    /// records: three 10-bit fields reading 2, 1 and 6.
    #[test]
    fn r2018_split_stream_group_matches_the_measured_widths() {
        let mut body = modern::tests::r2018_object_prefix(1);
        body.write_bs(2); // unnamed
        body.write_bs(1); // selectable
        body.write_bl(6); // member count
        let bits = crate::string_stream::tests::bits_of(&body);
        assert_eq!(bits.len(), 14 + 30, "measured budget is 30 bits of body");
        let payload = crate::string_stream::tests::build_payload(&bits, &[""]);
        let g = decode_object(&payload, 8, None, Version::R2018).unwrap();
        assert_eq!(g.name, "");
        assert_eq!(g.unnamed, 2);
        assert_eq!(g.selectable, 1);
        assert_eq!(g.num_members, 6);
    }

    /// Two single-bit flags cannot fill the measured budget — the
    /// pre-fix field list must now be rejected, not silently accepted.
    #[test]
    fn r2018_split_stream_group_rejects_the_old_boolean_field_list() {
        let mut body = modern::tests::r2018_object_prefix(1);
        body.write_b(true);
        body.write_b(true);
        body.write_bl(6);
        let bits = crate::string_stream::tests::bits_of(&body);
        let payload = crate::string_stream::tests::build_payload(&bits, &[""]);
        assert!(decode_object(&payload, 8, None, Version::R2018).is_err());
    }

    #[test]
    fn rejects_excessive_handle_count() {
        // Synthesize a stream where num_handles claims a count past the cap.
        let mut w = BitWriter::new();
        encode_tv_r2000(&mut w, b"G");
        w.write_bs(0);
        w.write_bs(1);
        // BL 0b00 tag then 32-bit LE = 200_001
        w.write_bl((MAX_GROUP_HANDLES + 1) as i32);
        let bytes = w.into_bytes();
        let mut c = BitCursor::new(&bytes);
        let err = decode(&mut c, Version::R2000).unwrap_err();
        assert!(matches!(&err, Error::SectionMap(msg) if msg.contains("ACAD_GROUP")));
    }
}
