//! R2004+ header XOR cipher (spec §4.1).
//!
//! The 0x6C bytes starting at file offset 0x80 are "encrypted" by XORing
//! against a deterministic 0x6C-byte magic sequence. The sequence is
//! generated by a Microsoft-flavor linear congruential generator:
//!
//! ```text
//! int randseed = 1;
//! while (sz--) {
//!     randseed *= 0x343FD;
//!     randseed += 0x269EC3;
//!     *p++ = (uint8_t)(randseed >> 0x10);
//! }
//! ```
//!
//! This is the same LCG used by Visual C++ `rand()` (Microsoft's
//! implementation), seeded with 1 and reading the high byte of bits 16..23
//! — which is where `rand()` takes its output. Autodesk did not invent a
//! new cipher; they just ran `rand()` for 108 iterations.
//!
//! # Legal note
//!
//! This is a trivial byte-sequence reproducible from the published spec.
//! It provides no confidentiality and no copyright attaches to the
//! sequence itself (a list of 108 bytes). All DWG readers compute it.

/// Expected length of the cipher stream — exactly 0x6C bytes.
pub const MAGIC_LEN: usize = 0x6C;

/// Generate the R2004+ XOR magic sequence (108 bytes).
///
/// The output is identical across every invocation because the LCG seed
/// is always 1. We regenerate on demand to keep the binary smaller than
/// baking it in as a literal and to let readers verify by inspection.
pub fn magic_sequence() -> [u8; MAGIC_LEN] {
    let mut out = [0u8; MAGIC_LEN];
    let mut seed: u32 = 1;
    for slot in &mut out {
        seed = seed.wrapping_mul(0x0003_43FD);
        seed = seed.wrapping_add(0x0026_9EC3);
        *slot = ((seed >> 0x10) & 0xFF) as u8;
    }
    out
}

/// XOR-decrypt (or re-encrypt — XOR is its own inverse) the 0x6C-byte
/// block in place.
pub fn xor_in_place(block: &mut [u8]) {
    let magic = magic_sequence();
    for (b, k) in block.iter_mut().zip(magic.iter()) {
        *b ^= *k;
    }
}

/// R2018+ encrypted section-page-header mask (spec §4.6):
///
/// ```text
/// secMask = 0x4164_536b XOR offset
/// ```
///
/// where `offset` is the file position of the 32-byte header. Each of the
/// 8 u32 words of the raw header is XORed with this constant mask. The
/// same mask works for encrypt and decrypt (it's XOR).
pub fn section_page_mask(offset: u32) -> u32 {
    0x4164_536B ^ offset
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The first 16 bytes of the sequence are published on page 24 of
    /// spec v5.4.1. Match them exactly.
    #[test]
    fn matches_spec_published_prefix() {
        let m = magic_sequence();
        let expected: [u8; 16] = [
            0x29, 0x23, 0xBE, 0x84, 0xE1, 0x6C, 0xD6, 0xAE, 0x52, 0x90, 0x49, 0xF1, 0xF1, 0xBB,
            0xE9, 0xEB,
        ];
        assert_eq!(&m[..16], &expected);
    }

    /// The full 0x6C-byte sequence from the spec.
    #[test]
    fn matches_spec_full_sequence() {
        let m = magic_sequence();
        let expected: [u8; 108] = [
            0x29, 0x23, 0xBE, 0x84, 0xE1, 0x6C, 0xD6, 0xAE, 0x52, 0x90, 0x49, 0xF1, 0xF1, 0xBB,
            0xE9, 0xEB, 0xB3, 0xA6, 0xDB, 0x3C, 0x87, 0x0C, 0x3E, 0x99, 0x24, 0x5E, 0x0D, 0x1C,
            0x06, 0xB7, 0x47, 0xDE, 0xB3, 0x12, 0x4D, 0xC8, 0x43, 0xBB, 0x8B, 0xA6, 0x1F, 0x03,
            0x5A, 0x7D, 0x09, 0x38, 0x25, 0x1F, 0x5D, 0xD4, 0xCB, 0xFC, 0x96, 0xF5, 0x45, 0x3B,
            0x13, 0x0D, 0x89, 0x0A, 0x1C, 0xDB, 0xAE, 0x32, 0x20, 0x9A, 0x50, 0xEE, 0x40, 0x78,
            0x36, 0xFD, 0x12, 0x49, 0x32, 0xF6, 0x9E, 0x7D, 0x49, 0xDC, 0xAD, 0x4F, 0x14, 0xF2,
            0x44, 0x40, 0x66, 0xD0, 0x6B, 0xC4, 0x30, 0xB7, 0x32, 0x3B, 0xA1, 0x22, 0xF6, 0x22,
            0x91, 0x9D, 0xE1, 0x8B, 0x1F, 0xDA, 0xB0, 0xCA, 0x99, 0x02,
        ];
        assert_eq!(m, expected);
    }

    /// XOR is its own inverse: encrypting then decrypting restores input.
    #[test]
    fn xor_is_involution() {
        let original: Vec<u8> = (0u8..(MAGIC_LEN as u8)).collect();
        let mut buf = original.clone();
        xor_in_place(&mut buf);
        assert_ne!(buf, original);
        xor_in_place(&mut buf);
        assert_eq!(buf, original);
    }

    #[test]
    fn section_page_mask_changes_with_offset() {
        assert_ne!(section_page_mask(0x100), section_page_mask(0x200));
        assert_eq!(section_page_mask(0) ^ 0x4164_536B, 0);
    }
}
